
# This file is used to configure the application properties.
spring:
  application:
    name: projectt2
  datasource:
    url: "jdbc:postgresql://localhost:5432/cr"
    username: postgres
    password: mysecretpassword
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    open-in-view: false


server:
  port: 3000